import type {
  MockIssue,
  MockLabelSummary,
  MockRepository,
  NavViewId,
  OverviewStat,
} from "@/types/issue";

export const CURRENT_USER_LOGIN = "gucchii";

export const mockRepositories: MockRepository[] = [
  {
    id: "1",
    fullName: "m-guchi/app-web",
    name: "app-web",
    private: false,
    color: "#3b82f6",
    openIssueCount: 32,
    lastActivityLabel: "2時間前",
  },
  {
    id: "2",
    fullName: "m-guchi/api-server",
    name: "api-server",
    private: true,
    color: "#22c55e",
    openIssueCount: 28,
    lastActivityLabel: "5時間前",
  },
  {
    id: "3",
    fullName: "m-guchi/mobile-app",
    name: "mobile-app",
    private: true,
    color: "#f59e0b",
    openIssueCount: 19,
    lastActivityLabel: "1日前",
  },
  {
    id: "4",
    fullName: "m-guchi/design-system",
    name: "design-system",
    private: true,
    color: "#8b5cf6",
    openIssueCount: 14,
    lastActivityLabel: "2日前",
  },
  {
    id: "5",
    fullName: "m-guchi/docs",
    name: "docs",
    private: false,
    color: "#64748b",
    openIssueCount: 8,
    lastActivityLabel: "3日前",
  },
];

export const mockLabelSummary: MockLabelSummary[] = [
  { name: "bug", color: "#ef4444", count: 45 },
  { name: "feature", color: "#22c55e", count: 38 },
  { name: "enhancement", color: "#8b5cf6", count: 20 },
  { name: "documentation", color: "#3b82f6", count: 12 },
  { name: "question", color: "#f59e0b", count: 7 },
];

export const navCounts: Record<NavViewId, number> = {
  all: 128,
  assigned: 18,
  created: 32,
  favorites: 9,
  recent: 24,
};

export const navViews: { id: NavViewId; label: string }[] = [
  { id: "all", label: "すべてのIssue" },
  { id: "assigned", label: "自分の担当" },
  { id: "created", label: "自分が作成" },
  { id: "favorites", label: "お気に入り" },
  { id: "recent", label: "最近更新されたIssue" },
];

export const overviewStats: OverviewStat[] = [
  { label: "オープンIssue", value: "128", diffLabel: "前日比 +12" },
  { label: "担当中", value: "18", diffLabel: "前日比 +3" },
  { label: "更新されたIssue", value: "24h", diffLabel: "前日比 +8" },
];

export const mockIssues: MockIssue[] = [
  {
    id: "i1",
    number: 123,
    title: "ログイン後にリダイレクトされない問題",
    body: "ログイン成功後、ダッシュボードにリダイレクトされるべきですが、ログインページのままになることがあります。\n\n再現手順は以下の通りです。\n\n1. ログインページにアクセス\n2. 正しいメールアドレスとパスワードを入力\n3. ログインボタンをクリック\n4. ダッシュボードにリダイレクトされない\n\n環境: Chrome / Windows 11",
    state: "open",
    repositoryFullName: "m-guchi/app-web",
    author: { login: "gucchii" },
    assignee: { login: "gucchii" },
    labels: [
      { name: "bug", color: "#ef4444" },
      { name: "high", color: "#f59e0b" },
    ],
    milestone: { name: "v1.2.0", progressPercent: 60 },
    commentCount: 4,
    comments: [
      {
        id: "c1",
        author: { login: "gucchii" },
        createdAtLabel: "2時間前",
        body: "追加情報です。特定の条件下で発生するようです。",
        reactionCount: 1,
      },
      {
        id: "c2",
        author: { login: "tanaka" },
        createdAtLabel: "1時間前",
        body: "同様の問題を確認しました。調査します。",
        reactionCount: 0,
      },
      {
        id: "c3",
        author: { login: "suzuki" },
        createdAtLabel: "45分前",
        body: "原因がわかりました。修正します。",
        reactionCount: 0,
      },
    ],
    activity: [
      { id: "a1", actorLogin: "gucchii", description: "が担当者に設定", createdAtLabel: "2時間前" },
      { id: "a2", actorLogin: "tanaka", description: "がコメントを追加", createdAtLabel: "1時間前" },
      { id: "a3", actorLogin: "suzuki", description: "がラベルを追加", createdAtLabel: "45分前" },
    ],
    createdAt: "2026-05-15T14:30:00+09:00",
    updatedAt: "2026-07-30T23:00:00+09:00",
    htmlUrl: "https://github.com/m-guchi/app-web/issues/123",
  },
  {
    id: "i2",
    number: 456,
    title: "ユーザー情報の取得に時間がかかる",
    body: "ユーザー情報取得APIのレスポンスが平均2秒以上かかっており、体感速度に影響しています。",
    state: "open",
    repositoryFullName: "m-guchi/api-server",
    author: { login: "gucchii" },
    assignee: null,
    labels: [
      { name: "performance", color: "#8b5cf6" },
      { name: "backend", color: "#3b82f6" },
    ],
    milestone: null,
    commentCount: 2,
    comments: [
      {
        id: "c4",
        author: { login: "tanaka" },
        createdAtLabel: "昨日",
        body: "N+1クエリが疑わしいです。",
        reactionCount: 2,
      },
    ],
    activity: [{ id: "a4", actorLogin: "tanaka", description: "がコメントを追加", createdAtLabel: "昨日" }],
    createdAt: "2026-07-20T09:00:00+09:00",
    updatedAt: "2026-07-29T18:00:00+09:00",
    htmlUrl: "https://github.com/m-guchi/api-server/issues/456",
  },
  {
    id: "i3",
    number: 789,
    title: "ダークモードの色が正しく反映されない",
    body: "一部のコンポーネントでダークモード切り替え時に配色が反映されないままになります。",
    state: "open",
    repositoryFullName: "m-guchi/mobile-app",
    author: { login: "suzuki" },
    assignee: { login: "gucchii" },
    labels: [
      { name: "bug", color: "#ef4444" },
      { name: "ui", color: "#3b82f6" },
    ],
    milestone: { name: "v1.2.0", progressPercent: 60 },
    commentCount: 6,
    comments: [],
    activity: [],
    createdAt: "2026-07-15T09:00:00+09:00",
    updatedAt: "2026-07-29T09:00:00+09:00",
    htmlUrl: "https://github.com/m-guchi/mobile-app/issues/789",
  },
  {
    id: "i4",
    number: 101,
    title: "レスポンシブデザインの崩れ",
    body: "タブレット幅（768px前後）でカードレイアウトが崩れます。",
    state: "open",
    repositoryFullName: "m-guchi/app-web",
    author: { login: "gucchii" },
    assignee: { login: "gucchii" },
    labels: [{ name: "ui", color: "#3b82f6" }],
    milestone: null,
    commentCount: 1,
    comments: [],
    activity: [],
    createdAt: "2026-07-10T09:00:00+09:00",
    updatedAt: "2026-07-28T09:00:00+09:00",
    htmlUrl: "https://github.com/m-guchi/app-web/issues/101",
  },
  {
    id: "i5",
    number: 55,
    title: "ボタンのバリエーションを追加",
    body: "outline / ghost 以外のバリエーションを追加してほしい。",
    state: "open",
    repositoryFullName: "m-guchi/design-system",
    author: { login: "gucchii" },
    assignee: null,
    labels: [{ name: "enhancement", color: "#8b5cf6" }],
    milestone: null,
    commentCount: 3,
    comments: [],
    activity: [],
    createdAt: "2026-07-08T09:00:00+09:00",
    updatedAt: "2026-07-27T09:00:00+09:00",
    htmlUrl: "https://github.com/m-guchi/design-system/issues/55",
  },
  {
    id: "i6",
    number: 12,
    title: "API仕様のエンドポイント一覧を更新",
    body: "新規追加したエンドポイントがドキュメントに反映されていません。",
    state: "open",
    repositoryFullName: "m-guchi/docs",
    author: { login: "tanaka" },
    assignee: { login: "gucchii" },
    labels: [{ name: "documentation", color: "#3b82f6" }],
    milestone: null,
    commentCount: 0,
    comments: [],
    activity: [],
    createdAt: "2026-07-05T09:00:00+09:00",
    updatedAt: "2026-07-26T09:00:00+09:00",
    htmlUrl: "https://github.com/m-guchi/docs/issues/12",
  },
  {
    id: "i7",
    number: 333,
    title: "バリデーションエラーのメッセージを改善",
    body: "エラーメッセージが技術的すぎるため、ユーザー向けの文言に修正したい。",
    state: "open",
    repositoryFullName: "m-guchi/api-server",
    author: { login: "gucchii" },
    assignee: { login: "gucchii" },
    labels: [
      { name: "enhancement", color: "#8b5cf6" },
      { name: "backend", color: "#3b82f6" },
    ],
    milestone: null,
    commentCount: 5,
    comments: [],
    activity: [],
    createdAt: "2026-07-01T09:00:00+09:00",
    updatedAt: "2026-07-25T09:00:00+09:00",
    htmlUrl: "https://github.com/m-guchi/api-server/issues/333",
  },
  {
    id: "i8",
    number: 654,
    title: "プッシュ通知が届かない",
    body: "特定の端末でプッシュ通知が届かない不具合が報告されています。",
    state: "closed",
    repositoryFullName: "m-guchi/mobile-app",
    author: { login: "suzuki" },
    assignee: { login: "suzuki" },
    labels: [{ name: "bug", color: "#ef4444" }],
    milestone: null,
    commentCount: 2,
    comments: [],
    activity: [],
    createdAt: "2026-06-01T09:00:00+09:00",
    updatedAt: "2026-07-20T09:00:00+09:00",
    htmlUrl: "https://github.com/m-guchi/mobile-app/issues/654",
  },
];
