-- リリース候補の修正系列（#4317）。
CREATE TABLE `ReleaseFixSeries` (
  `id` VARCHAR(191) NOT NULL,
  `repositoryFullName` VARCHAR(191) NOT NULL,
  `releasePrNumber` INTEGER NOT NULL,
  `releaseVersion` VARCHAR(64) NULL,
  `originBaseSha` VARCHAR(64) NOT NULL,
  `originHeadSha` VARCHAR(64) NOT NULL,
  `sourceKind` VARCHAR(32) NOT NULL,
  `causeClass` VARCHAR(32) NOT NULL,
  `sourceKey` VARCHAR(64) NOT NULL,
  `items` JSON NOT NULL,
  `issueNumber` INTEGER NOT NULL,
  `fixPrNumber` INTEGER NULL,
  `fixPrMergedAt` DATETIME(3) NULL,
  `acceptedExtraPrs` JSON NULL,
  `status` VARCHAR(32) NOT NULL,
  `stopReason` TEXT NULL,
  `activeKey` VARCHAR(255) NULL,
  `parentId` VARCHAR(40) NULL,
  `generation` INTEGER NOT NULL DEFAULT 1,
  `rebuildClaimedAt` DATETIME(3) NULL,
  `successorPrNumber` INTEGER NULL,
  `successorBaseSha` VARCHAR(64) NULL,
  `successorHeadSha` VARCHAR(64) NULL,
  `createdByUserId` VARCHAR(40) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `ReleaseFixSeries_activeKey_key`(`activeKey`),
  INDEX `ReleaseFixSeries_repositoryFullName_releasePrNumber_idx`(`repositoryFullName`, `releasePrNumber`),
  INDEX `ReleaseFixSeries_status_idx`(`status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
