-- リリース全体のAIレビューをDispatchJobで管理する（#4238）。
ALTER TABLE `DispatchJob` MODIFY `kind` ENUM('LAUNCH','INTERRUPT','KILL','QUESTION','INSTRUCTION','CROSS_REPO_QUESTION','MANUAL_STEP','MANUAL_STEP_ABORT','PLAN_REVIEW','SELF_UPDATE','CODE_REVIEW','PREVIEW','REBOOT','CODEX_PAIRING','MANUAL_STEP_SESSION','PR_REVIEW','REVIEW_FIX','CHAT_TURN','RELEASE_VERIFY','RELEASE_REVIEW') NOT NULL DEFAULT 'LAUNCH';

ALTER TABLE `DispatchHost` ADD COLUMN `releaseReviewCapable` BOOLEAN NULL;
