-- リリースPRの統合検証をDispatchJobで管理する（#4237）。
ALTER TABLE `DispatchJob` MODIFY `kind` ENUM('LAUNCH','INTERRUPT','KILL','QUESTION','INSTRUCTION','CROSS_REPO_QUESTION','MANUAL_STEP','MANUAL_STEP_ABORT','PLAN_REVIEW','SELF_UPDATE','CODE_REVIEW','PREVIEW','REBOOT','CODEX_PAIRING','MANUAL_STEP_SESSION','PR_REVIEW','REVIEW_FIX','CHAT_TURN','RELEASE_VERIFY') NOT NULL DEFAULT 'LAUNCH';

ALTER TABLE `DispatchHost` ADD COLUMN `releaseVerifyCapable` BOOLEAN NULL;
