-- AlterTable
-- develop側で先にマージされた20260818130000（SELF_UPDATE追加）が、同じenumを
-- MODIFY COLUMNで丸ごと置き換える際にMANUAL_STEP_ABORT（#1882・20260818090000で追加済み）を
-- 落としていたため、値を戻す。既存行の書き換えは不要。
ALTER TABLE `DispatchJob`
    MODIFY COLUMN `kind` ENUM('LAUNCH', 'INTERRUPT', 'KILL', 'QUESTION', 'INSTRUCTION', 'CROSS_REPO_QUESTION', 'MANUAL_STEP', 'MANUAL_STEP_ABORT', 'PLAN_REVIEW', 'SELF_UPDATE') NOT NULL DEFAULT 'LAUNCH';
